# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=140)),
                ('amueblada', models.BooleanField(default=True)),
                ('servicios', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=140)),
                ('cochera', models.BooleanField(default=True)),
                ('recamara', models.CharField(max_length=140)),
                ('plantas', models.CharField(max_length=140)),
                ('patio', models.BooleanField(default=True)),
                ('depocito', models.CharField(max_length=140)),
                ('foto', models.ImageField(upload_to='fotocasa')),
            ],
        ),
    ]
