# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='patios',
            new_name='patio',
        ),
    ]
