# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_auto_20160911_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='amueblada',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=140),
        ),
    ]
