# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0003_auto_20160911_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='amueblada',
            field=models.BooleanField(default=True),
        ),
    ]
