# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0005_auto_20160916_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
