# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0006_casa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='municipio',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
