# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0008_auto_20160916_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='amueblada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cochera',
            field=models.BooleanField(max_length=140),
        ),
        migrations.AlterField(
            model_name='casa',
            name='deposito',
            field=models.IntegerField(max_length=140),
        ),
        migrations.AlterField(
            model_name='casa',
            name='municipio',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='casa',
            name='patio',
            field=models.BooleanField(max_length=140),
        ),
        migrations.AlterField(
            model_name='casa',
            name='plantas',
            field=models.IntegerField(max_length=140),
        ),
        migrations.AlterField(
            model_name='casa',
            name='recamaras',
            field=models.IntegerField(max_length=140),
        ),
    ]
