# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0010_auto_20160917_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='deposito',
            new_name='depósito',
        ),
        migrations.RenameField(
            model_name='casa',
            old_name='direccion',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='casa',
            old_name='recamaras',
            new_name='recámaras',
        ),
        migrations.RenameField(
            model_name='casa',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
