# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0012_casa_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
