# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0014_auto_20161207_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='recmaras',
            new_name='recamaras',
        ),
    ]
