# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.IntegerField(blank=True, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='user/back')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='user/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
