# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='municpio',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
