# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160917_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_birth',
        ),
    ]
